<?php

namespace App\Filament\Resources\TourPackages\Schemas;

use Filament\Infolists\Components\IconEntry;
use Filament\Infolists\Components\ImageEntry;
use Filament\Infolists\Components\TextEntry;
use Filament\Schemas\Schema;

class TourPackageInfolist
{
    public static function configure(Schema $schema): Schema
    {
        return $schema
            ->components([
                TextEntry::make('destination.name')
                    ->label('Destination'),
                TextEntry::make('slug'),
                TextEntry::make('title')
                    ->columnSpanFull(),
                TextEntry::make('category')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('tag')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('excerpt')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('intro')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('best_for')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('duration')
                    ->placeholder('-'),
                TextEntry::make('difficulty')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('base_price_idr')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('base_price_usd')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('price_note')
                    ->placeholder('-')
                    ->columnSpanFull(),
                ImageEntry::make('cover_image')
                    ->placeholder('-'),
                TextEntry::make('cover_alt')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('gallery')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('pickup_areas')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('pickup_label')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('group_type')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('highlights')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('includes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('excludes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('notes')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('details')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('good_to_know')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('policies')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('testimonials')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('rating')
                    ->numeric()
                    ->placeholder('-'),
                TextEntry::make('review_count')
                    ->numeric(),
                TextEntry::make('review_source')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('styles')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('sort_order')
                    ->numeric(),
                IconEntry::make('is_featured')
                    ->boolean(),
                IconEntry::make('is_active')
                    ->boolean(),
                TextEntry::make('seo')
                    ->placeholder('-')
                    ->columnSpanFull(),
                TextEntry::make('created_at')
                    ->dateTime()
                    ->placeholder('-'),
                TextEntry::make('updated_at')
                    ->dateTime()
                    ->placeholder('-'),
            ]);
    }
}
